name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up Python
        run: uv python install 3.12
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Run ruff linter
        run: uv run ruff check src/
      - name: Run ruff formatter
        run: uv run ruff format --check src/

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        django-version: ["4.2", "5.1", "5.2"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install Django ${{ matrix.django-version }}
        run: |
          uv add "django>=${{ matrix.django-version }},<${{ matrix.django-version }}.99"
      - name: Run tests
        run: uv run ./run.sh test
      - name: Show versions
        run: |
          uv run python --version
          uv run django-admin --version
